### ISSUE TITLE
Comment Grey Is Too Dark With Dark Theme

### ISSUE THREAD

**Issue by macMikey** [bhall2001/revigniter-dark-syntax#7]
If the comment is all in uppercase, the appearance is ok, but for bigger blocks, especially for ones with mixed-case, it's hard to read the comments.  Here's an example for you to try, from Gugliermo's dropbox library:

// ------------------------------------------------------------------
// phxDropboxLib 1.09
//
// (c) 2001-2015 Phoenix Sistemi & Automazione s.a.g.l. - Muralto (TI)
// Switzerland - All Rights Reserved Worldwide.
// http://www.phoenixsea.ch/
//
// You can use this library under the terms of the MIT License
//
// Support eMail : guglielmo.braguglia@phoenixsea.ch
//
// If you want to support the developement you can do a free donation by PayPal
// to this eMail :  guglielmo.braguglia@citynet.ch  - Thanks !
//
// The DB core REST API is documented at https://www.dropbox.com/developers/core/docs
//
// Revision History :
// 1.02 : first public release
// 1.03 : added pLimit and pList to function phx_DropboxGetFileInfo
//         : added pLimit to function phx_DropboxGetFileList
//         : added new function phx_DropboxMoveFile pRoot, pFromPath, pToPath
//         : corrected some Err: messages
//         : some corrections made by Mike Kerner marked as : #mikey
// 1.04 : fixed WriteFile code on mobile devices (PUSH)
//         : corrections made by Mike Kerner marked as : #mikey
// 1.05 : fixed a really obscure issue that could cause a failure on mobile after writing a file
//         : added some documentation to the code here and there
//         : corrections made by Mike Kerner marked as : #mikey
// 1.06 : for mobile, EVERY URL has to be sent through rfcURLEncode, or it will not be handled.
//         : corrections made by Mike Kerner marked as : #mikey
// 1.07 : fixed an unecessary URLEncode in phx_DropboxWriteFile
//         : fixed an unecessary URLEncode in phx_DropboxGetFileList
//         : added new function phx_DropboxCreateLinkToFile pRoot, pPath, pShortURL
//         : correction and new function made by Trevor DeVore marked as : #TKD
// 1.08 : STILL fiddling with paths and filenames to deal with reserved characters and spaces.
//         : LC treats URL's differently on desktop and mobile.
//         : Changes made by Mike Kerner, marked as: #mikey
// 1.09 : Added rfcURLDecode and isHex so when we retrieve the filenames we can (easily) get a human-readable version
//         : Added isHex, used by rfcURLDecode to check if the two characters after a % are hex or not.  IN THEORY every
//         : % in a filename/path should be followed by a hex pair (indicating the ASCII character to be substituted), but I'm not
//         : assuming anything.
//         : Made rfcURLEncode un-private b/c we should be able to encode a filename before we pass it with a path, because if a filename
//         : has slashes as part of the name, we can't encode them later (since we wouldn't know if the slashes are part of the name
//         : like /myHappyPlace/filename or if they were part of a filename like "2/20/15 files".
//         : Also added oreOpenStack, openStack, openCard, closeCard, and closeStack handlers so a parent stack doesn't freak out
//         : if this gets opened by the developer.
//         : Changes are by Mike Kerner, marked as: #mikey
//
// ------------------------------------------------------------------

**Comment by macMikey** [comment]
Here are a couple of screenshots:
![screen shot 2015-10-19 at 16 40 29](https://cloud.githubusercontent.com/assets/10867016/10590740/5e3d3df8-7680-11e5-8211-5a9c1ca332ac.png)
![screen shot 2015-10-19 at 16 40 54](https://cloud.githubusercontent.com/assets/10867016/10590741/5e4a9624-7680-11e5-9f1b-7eb24a082642.png)

**Comment by bhall2001** [comment]
Try out version 0.3.2 and let me know if that is light enough. Thanks for the feedback!
Bob

**Comment by macMikey** [comment]
much better, thank you.

**Comment by macMikey** [comment]
You can close this one.
